### ISSUE TITLE
TODO: Toggles - Button groups - multiple icons

### ISSUE THREAD

**Issue by normanzb** [englishtown/gudstrap#15]

**Comment by jacksky007** [comment]
Can anyone help me explain the difference between icons and multiple icons. I think icons toggle is just a special case of multiple icons toggles. Or something else is different?

**Comment by jacksky007** [comment]
And what js API should I expose for button group toggles. Dose anyone have some suggestions?

**Comment by mikaelkaron** [comment]
@jacksky007 : What do you mean by _API_, JavaScript _API_?

**Comment by jacksky007** [comment]
@mikaelkaron Yes. Because I don't know what exact functionality it should provide or when and how it will be used. Right now, I just simply add the visual effect of toggling on ef-component page. Maybe I can leave it and wait until @phariel finishes standard toggles. Then I can learn from that.

**Comment by mikaelkaron** [comment]
Maybe. I'd like us to simply copy the 'standard' way used in the other jQuery plugins.

Quickly parsing the current js docs I'd guess:
- One 'constructor' method named after the plugin taking one `object` with options as a parameter (eg: `.toggle(options)`).

> All methods should accept an optional options object, a string which targets a particular method, or nothing (which initiates a plugin with default behavior):
- Plugins should support `.noConflict`

> Sometimes it is necessary to use Bootstrap plugins with other UI frameworks. In these circumstances, namespace collisions can occasionally occur. If this happens, you may call .noConflict on the plugin you wish to revert the value of.
- Executing functions should be through the same method (eg: `.toggle('on')` or `.toggle('off')`)
- Events raised by the plugins should be standard DOM events with the plugin name as a namespace (eg: `toggled.toggle`) and for each action two events should get triggered:

> Bootstrap provides custom events for most plugin's unique actions. Generally, these come in an infinitive and past participle form - where the infinitive (ex. show) is triggered at the start of an event, and its past participle form (ex. shown) is trigger on the completion of an action.
- The constuctor should be exposed

> Each plugin also exposes its raw constructor on a Constructor property: $.fn.popover.Constructor. If you'd like to get a particular plugin instance, retrieve it directly from an element: $('[rel=popover]').data('popover').

---

All of these are documented at the top of [the javascript doc](http://englishtown.github.io/bootstrap/javascript/)
