### ISSUE TITLE
Increase base font size for components

### ISSUE THREAD

**Issue by normanzb** [englishtown/gudstrap#26]
According to discussion with @chrometaphore .

The default font size for body text should be 12px.
The default font size for components should be 14px (which current is 12px)

We probably need another batch of font size definitions:

```
@font-size-cmp-base:          14px;
@font-size-cmp-small:         ceil(@font-size-base * 1); // ~14px
@font-size-cmp-large:          ceil(@font-size-base * 1); // ~14px
@font-size-cmp-xlarge:        ceil(@font-size-base * 1.142857); // ~16px
```

_thx @ika18 to point it out in #22 ._

**Comment by mikaelkaron** [comment]
@faceach says it's completed, so closing.
