### ISSUE TITLE
"back to top" link not working on components page

### ISSUE THREAD

**Issue by mikaelkaron** [englishtown/gudstrap#4]

**Comment by jacksky007** [comment]
First, I disable JS, and it works, so are other pages.
Second, I unbind event handlers of the link on components page, it also works.
So, I think there may be some issues in JS. I'll try to find and fix them.

**Comment by jacksky007** [comment]
I think I get the point.
https://github.com/englishtown/bootstrap/blob/develop/assets/js/application.js#L19-L21
Does anyone have any suggestion on this? @faceach @normanzb

**Comment by jacksky007** [comment]
Sorry, I find it's not a problem of JS. I think it's caused by missing closing tag, so the link is wrapped into that div.

**Comment by mikaelkaron** [comment]
Next time try using `closes englishtown/bootstrap#4` instead (as it will close the corresponding ticket in the right repository)
