### ISSUE TITLE
Gudstrap js components have to be AMD compliant

### ISSUE THREAD

**Issue by mikaelkaron** [englishtown/gudstrap#75]
As we're moving away from having _any_ global js objects (this includes `$` and `jQuery`) we need to start thinking how GUDstap fits into that.

On the one hand we don't want to create merge issues with upstream, and on the other hand we don't want globals. The solution would be to wrap our components during the build step. I see two different ways this can be done:
- Use [r.js](/jrburke/r.js) combined with the [shadow plugin](/troopjs/troopjs-requirejs/blob/develop/shadow.js).
- Manually alter `gudstrap.js` to be AMD (or even better UMD) compliant.

My vote is for the second solution as it looks to be the least intrusive.

**Comment by faceach** [comment]
Will finish by 10/29
