### ISSUE TITLE
TODO: Glyphicon helper class - warning icon, success icon and error icon

### ISSUE THREAD

**Issue by normanzb** [englishtown/gudstrap#9]
_For graphic detail, please checkout the PSD in orphaned branch._

The idea is to have some sort of helper classes that automatically display the validation state icon on the right side of containing box, when the containing box gain its state class.

e.g:

```
<div class="has-warnning">
  <input class="form-control" />
  <span class="glyph-helper-warning"></span>
</div>
```

`glyph-helper-warning` should display the warning icon when `has-warnning` is set on the containing box.
- the helper classes should compatible with bootstrap form validation state (see component section of the doc)
- not sure if the helper class should sit inside the glyph repository or current one.

**Comment by phariel** [comment]
@normanzb One question: Which format of file we wanna put all custom icons into? An icon PNG image or a FONT?

**Comment by jacksky007** [comment]
Maybe we need font awesome.

**Comment by mikaelkaron** [comment]
`font` for sure. for now we can look at font awesome, but all icons should be font based.

**Comment by jacksky007** [comment]
So we need download the font files and the css file. Yes?

**Comment by mikaelkaron** [comment]
We should include it in our repo, yes.

**Comment by normanzb** [comment]
@phariel i would go with font

**Comment by phariel** [comment]
@normanzb sure, I saw group button icons using font-awesome in previous commits. I merge down code from englishtown/bootstrap/develop to my bootstrap/develop every night, therefore I could sync with your code. 
Thanks. :smile_cat:
